BUNDLES = [
    "//apps/annotationx/api:onos-apps-annotationx-api",
    "//apps/annotationx/app:onos-apps-annotationx-app",
]

onos_app(
    category = "Utility",
    description = "Annotation Extension",
    included_bundles = BUNDLES,
    title = "Annotation Extension ",
    url = "https://www.ict.com",
)
